export const statsData = [
    { text: "citi.com", count: "4.2M", percent: "52", arrowImage: "success" },
    { text: "amazon.com", count: "2.1M", percent: "34", arrowImage: "error" },
    { text: "netflix.com", count: "1.5M", percent: "25", arrowImage: "success" },
    { text: "apple.com", count: "3.8M", percent: "47", arrowImage: "success" },
    { text: "google.com", count: "2.5M", percent: "40", arrowImage: "error" },
    { text: "facebook.com", count: "1.9M", percent: "55", arrowImage: "success" },
    { text: "twitter.com", count: "3.0M", percent: "33", arrowImage: "error" },
    { text: "microsoft.com", count: "2.8M", percent: "28", arrowImage: "success" },
    { text: "adobe.com", count: "4.5M", percent: "60", arrowImage: "success" },
    { text: "linkedin.com", count: "1.2M", percent: "12", arrowImage: "error" },
    { text: "walmart.com", count: "3.3M", percent: "45", arrowImage: "success" },
    { text: "ebay.com", count: "2.4M", percent: "30", arrowImage: "error" },
    { text: "paypal.com", count: "1.6M", percent: "20", arrowImage: "success" },
    { text: "spotify.com", count: "3.9M", percent: "50", arrowImage: "success" },
    { text: "uber.com", count: "2.2M", percent: "35", arrowImage: "error" },
    { text: "airbnb.com", count: "4.0M", percent: "53", arrowImage: "success" },
];
